In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([[1.0, 2.0, 3.0],
              [4  , 5  ,   6]])

In [4]:
c = np.array([[[1,2,3],
               [4,5,6]],
             
               [[4,5,6],
               [7,8,9]]])

In [5]:
d = np.array([1,2,3,4,5], ndmin = 5)   # Fifth dimentional array

In [6]:
a.shape, b.shape, c.shape    # array shape

((3,), (2, 3), (2, 2, 3))

In [7]:
a.ndim, b.ndim, c.ndim, d.ndim     # array dimention

(1, 2, 3, 5)

In [8]:
a.dtype, b.dtype, c.dtype    # aray data type

(dtype('int32'), dtype('float64'), dtype('int32'))

In [9]:
a.nbytes, b.nbytes, c.nbytes    # array memery useses

(12, 48, 48)

In [10]:
a.data, b.data, c.data, d.data # array memory location

(<memory at 0x0000021AF1E53640>,
 <memory at 0x0000021AF1F84940>)

In [11]:
new = b.astype('i')

In [12]:
new

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [13]:
new2 = new.copy()

In [14]:
new3 = new.view()

In [15]:
new2

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [16]:
print(new2.base)

None


In [17]:
print(new3.base)

[[1 2 3]
 [4 5 6]]


# Array Iterating 

In [18]:
b2 = b.astype(int)

In [19]:
b2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
for x in b2:
    print(x)

[1 2 3]
[4 5 6]


In [21]:
for x in b2:
    for y in x:
        print(y)

1
2
3
4
5
6


In [22]:
c2 = c.astype(int)

In [23]:
c2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [24]:
for x in c2:
    print(x)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


# Array Creation

In [25]:
array1 = np.array([1,2,3], dtype = 'int')

In [26]:
array1

array([1, 2, 3])

In [27]:
zeros = np.zeros((3,3), dtype='int')

In [28]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [29]:
ones = np.ones((3,3), dtype = 'int')

In [30]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [31]:
full = np.full((3,3), 2)   # we can fill array by np.full()

In [32]:
full

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [33]:
identity = np.identity(3, dtype = 'int')   # identity matrix

In [34]:
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
eye = np.eye(3,3, 1, dtype = 'int')   # '1' here this value shift left or right from IDENTITY matrix

In [36]:
eye

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [37]:
arange = np.arange(1, 30, 2)   # shift + tab in bracket

In [38]:
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [39]:
linspace = np.linspace(1, 10, 5)   # '5' devide 1 to 10 , 5 times

In [40]:
linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Array Indexing

In [41]:
rand_arr = np.random.randint(1,10, size = (3,3))

In [42]:
rand_arr

array([[9, 1, 6],
       [3, 6, 7],
       [8, 8, 6]])

In [43]:
rand_arr [1,1]   # Calling 9

6

In [44]:
rand_arr [1][1]   # Calling 9

6

In [45]:
array1_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                      [[7, 8, 9], [10, 11, 12]]])

In [46]:
array1_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
array1_3d[0,1,0]   # Accessing 3d Array

4

In [48]:
array1_3d[0][1][0]

4

In [49]:
arr_3d = np.random.randint(1, 10, size = (2,3,3))  # Generating Array bu random number

In [50]:
arr_3d

array([[[7, 7, 6],
        [9, 8, 9],
        [5, 5, 9]],

       [[3, 8, 3],
        [1, 1, 9],
        [8, 8, 6]]])

# Array Slicing

In [51]:
a

array([1, 2, 3])

In [52]:
a[0:2] # '2' means up to two

array([1, 2])

In [53]:
a[1:]

array([2, 3])

In [54]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [55]:
ones[0:2]

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
ones[0:2, 0:2]  # slicing cloumn

array([[1, 1],
       [1, 1]])

In [58]:
rand_arr

array([[9, 1, 6],
       [3, 6, 7],
       [8, 8, 6]])

In [59]:
rand_arr[1:, 1:]    # wow

array([[6, 7],
       [8, 6]])

# Manipilating Array Shapes

1. reshape()
2. resize()
3. flatten()
4. ravel()

**reshape()**

In [60]:
array_2d = np.array([[1,2,3],
                    [4,5,6]])

In [61]:
array_2d.shape

(2, 3)

In [62]:
array_2d.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
array_2d.shape

(2, 3)

In [64]:
reshaped = np.reshape(array_2d, (3,2))

In [65]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
reshaped.shape

(3, 2)

**resize()**

In [67]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
resized = np.resize(array_2d, (3,3))

In [69]:
resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [70]:
resized2 = np.resize(array_2d, (4,3))

In [71]:
resized2   # array repeating

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**ravel()**

In [72]:
rav = np.random.randint(1, 10, (2,3), dtype = 'int')

In [73]:
rav

array([[3, 3, 1],
       [1, 8, 4]])

In [74]:
raveled = np.ravel(rav)

In [75]:
raveled       # this converts to 1d array

array([3, 3, 1, 1, 8, 4])

In [76]:
raveled.shape

(6,)

In [77]:
rav

array([[3, 3, 1],
       [1, 8, 4]])

In [78]:
raveled

array([3, 3, 1, 1, 8, 4])

In [79]:
raveled[0] = 0

In [80]:
raveled  # in ravel() we can change the elements , real array =(rav), আসল অ্যারে

array([0, 3, 1, 1, 8, 4])

In [81]:
rav

array([[0, 3, 1],
       [1, 8, 4]])

**flatten()**

In [82]:
rav

array([[0, 3, 1],
       [1, 8, 4]])

In [83]:
flattened = rav.flatten()    # return a copy of array, always allocates new memory

In [84]:
flattened     # it also makes a 1d array

array([0, 3, 1, 1, 8, 4])

In [85]:
flattened[1] = 0

In [86]:
flattened

array([0, 0, 1, 1, 8, 4])

In [87]:
rav     # flatten can't change REAL array

array([[0, 3, 1],
       [1, 8, 4]])

# Stacking
| Function | Description |
|---|---|
| `vstack()` | This function stacks arrays vertically. |
| `dstack()` | This function stacks arrays depth-wise along the third axis. |
| `hstack()` | This function stacks arrays horizontally. |
| `column_stack()` | This function stacks one-dimensional arrays as columns to create a two-dimensional array. |
| `row_stack()` | This function stacks arrays vertically. |
| `concatenate()` | This function concatenates a list or a tuple of arrays. |


**Horizontal Stack**

In [88]:
aa = np.arange(1, 10).reshape(3,3)

In [89]:
aa

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
bb = aa * 2

In [91]:
bb

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [92]:
np.hstack(aa)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.hstack((aa, bb))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [94]:
np.column_stack((aa, bb))

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

In [95]:
np.concatenate((aa, bb), axis = 1)

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])

**Verticle Stack**

In [96]:
np.vstack((aa, bb))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [97]:
np.row_stack((aa, bb))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [98]:
np.concatenate((aa, bb), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

**Depth Stack**

In [99]:
np.dstack((aa, bb))

array([[[ 1,  2],
        [ 2,  4],
        [ 3,  6]],

       [[ 4,  8],
        [ 5, 10],
        [ 6, 12]],

       [[ 7, 14],
        [ 8, 16],
        [ 9, 18]]])

# Creating the Filter Array


In [100]:
arange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [106]:
# returning which number is devided by 3

filter_arr = []

for i in arange:
    if (i % 3 == 0):
        filter_arr.append(True)
    else:
        filter_arr.append(False)

new_array = arange[filter_arr]

print(new_array)

[ 3  9 15 21 27]
